version: 0.2

phases:
  install:
    commands:
       - /usr/local/bin/docker-entrypoint.sh elasticsearch -Ediscovery.type=single-node &
       - yum -y install python3
       - yum -y install git
       - pip3 install wheel
  build:
    commands:
       - python3 setup.py sdist bdist_wheel
  post_build:
    commands:
       - pip3 install pytest
       - pip3 install nose
       - pip3 install -r requirements_web_es6.txt
       - pytest tests --junitxml=test_result.xml
reports:
  pytest:
    files:
       - test_result.xml
artifacts:
  files:
    - dist/*
  discard-paths: yes